### ISSUE TITLE
differences from kmonad

### ISSUE THREAD

**Issue by smallstepman** [waynr/qsk#2]
Hi! Is this something similar to https://github.com/kmonad/kmonad ?

**Comment by waynr** [comment]
@smallstepman hey, thanks for sharing that! I had not idea that existed, though admittedly I didn't look super hard before starting this project. But yes, that looks like a very similar project to qsk, albeit more mature.

Starting with similarities:

* Both are inspired by QMK
* Both are intended to operate at the software (rather than firmware) level 
* Both implement a layers-based remapping system

The biggest differences are definitely in project maturity and approach to configuration:

* In terms of project maturity, qsk currently only supports one keyboard remapping functions (tap toggle) whereas kmonad appears to support many different remapping functions. qsk has a ways to go to catch up.
* In terms of approaches to configuration:
  * qsk configuration currently must be in Rust, though I just merged a PR (#1) that introduces a DSL via procedural macro to make this much more user friendly.
    * still not greate because it means users must compile their own binary. i do have a plan to make this easier using `cargo generate`
    * i do have in mind an approach similar to kmonad's though I haven't though too much on DSL syntax yet. not sure when i'll get to this.
  * kmonad looks like it has a lisp-like keyboard remapping definition language with support for aliases, which is super cool and definitely more user-friendly than qsk.

One point worth mentioning where qsk may be able to differentiate itself is that it may be possible in the future to target keyboard microcontrollers so that qsk could be used as both a software-level remapper and firmware (so it could compete with both kmonad and QMK).

**Comment by smallstepman** [comment]
cool, very nice! I've been using QMK, ZMK and kmonad throughout last 2 years, and there is a room for improvement in each and every one. There is also not a single solution which would encompass all the input/peripheral things (whether built-in laptop keyboard, or, external wireless custom made ergo with trackball). 

QMK is mostly for wireless and AVR MCUs (makes it useless for my use case). 

ZMK is very cool, built on top of Zephyr, but all the code is in C, and I believe that hinders development velocity (bunch of very old PRs), but technically makes it able to build any sort of ergo keyboard with whatever features one desires. But I don't see a future where I can use ZMK to handle my laptop keyboard.

kmonad is also very cool, but, it introduces lag, the experience is not as good as the one I get on vanilla keyboard, or with ZMK/QMK, but it's good enough, been using it as a daily driver for a year now.

There is also no crate in Rust, which would allow to embed kbr remapper into other software, say, you're building some native app to run on linux, and you want to allow your users to hold-tap `a` key to trigger two different actions. The _remapper logic_ could ultimately be reused for all use cases: built-in kbr, external kbr with flashable MCU, and functionality to bake into other programs, perhaps even as a webassembly module.

If you were ever go down the route of targeting MCUs, it probably wouldn't hurt to consider using RTOS, which would bring support for plethora of chips, and provide mature plugin system:
- https://micro.ros.org/docs/concepts/rtos/comparison/
- https://github.com/hashmismatch/freertos.rs
- https://github.com/lobaro/FreeRTOS-rust
- https://github.com/lupyuen/rust-nuttx
- https://github.com/no1wudi/nuttx.rs
- https://github.com/tylerwhall/zephyr-rust
- https://www.zephyrproject.org/embedding-rust-into-zephyr-firmware-using-c-bindgen/

another thing to consider for you on MCU route (again, if you ever decided to go there), is to think about supporting other peripherals, both input and output:
- trackpoints/joysticks
- trackballs/mouse laser sensors
- pedals
- gyro/accelometer
- trackpads
- wacom-style tablets
- eink/oled screens
- leds
- wild stuff: thermal printers, or https://www.wired.com/story/facebook-wrist-wearable-human-computer-interactions/

I haven't yet dig your code, how does it work? Do you register set of `xmodmap` commands based on layout provided in `remap!` macro, or are you grabbing input and piping it trough the binary to output ...what? 

I don't think recompiling on each change is an issue, as long as it would boost the performance (lower latency). Sure, having one step less while re-configuring layout wouldn't hurt, but then again, I only modify layout once every few weeks once it settled down. But probably that's something a newcomer would enjoy greatly. Then again, there are other helpers we could use, like `when-changed config-file.rs "cargo run && pkill qsk && qsk /input/kbr"`, which would automatically recompile and rerun `qsk` on each config change.

What do you think? I'd be very excited to lend my hand if you were to go all-in on this.

edit: DSL would be nice, but tbh every single one I used sucked is some way. I'll always run into an issue of naming my mappings, then placing the name into the kbr layout which forces me to reformat everything, e.g. keypad example:
```
layer-1 = {
1  2  3
4  long_mapping_name 6
7  8  9
}

layer-2 = {
a  b  c
d  e  f 
i  j  k
} 
```
its a trivial example, but when there are 12 columns, it gets ugly, and I have to spend time counting space characters and such. Honestly, the best DSL I can imagine, is something which will take care of formatting automatically, like org-table in emacs, [vim-table mode](https://www.youtube.com/watch?v=sK2IH1hiDkw)(very similar to org-table), or even sth like Excel/Google spreadsheets (however those, unlike two previous candidates, cannot be nicely rendered on GitHub), I'm sure there is something similar for vscode too.

**Comment by smallstepman** [comment]
Btw, there is also https://karabiner-elements.pqrs.org for macOS

**Comment by waynr** [comment]
Just to be up front I do plan to take a few weeks off from working on this project. I've been spending around 1-2 hours a day on top of my usual work and home responsibilities to get the project to its current state (my first ever crates.io releases!). I definitely plan to continue iterating and improving this project over time, hopefully in the near future (after I've had a break to work on some other things). I have begun streaming my open source coding sessions on Twitch at https://twitch.tv/uuayn -- if you want to check it out sometime I'd be happy to answer any questions you have about qsk.

I recommend checking out the README -- there are instructions on using `cargo generate` to produce your own qsk project with an example keymapping ready for you to define to your liking. As I mentioned in my last response, it's pretty barebones as far as features are concerned right now. But if you can get it building and try your own keymaps using the proc macro DSL maybe you can find bugs I haven't run into yet.

I'm going out of town tomorrow but after I get back next weekend I'll try to circle back and give more thoughtful responses to your post. For now I can briefly answer a few questions:

> I haven't yet dig your code, how does it work?

Going in-depth to explain this will take more time than I have now, but I'll be happy to put together some diagrams and architecture docs when I have time. Also happy to do a code walkthrough on the abovementioned twitch stream.

> Do you register set of xmodmap commands based on layout provided in remap! macro, or are you grabbing input and piping it trough the binary to output ...what?

`qsk` grabs input and pipes it through a series of layers to get a final output that gets sent through a virtual input device, similar to `kmonad`.

> I don't think recompiling on each change is an issue, as long as it would boost the performance (lower latency). 

I consider the project in its current state to be more "proof-of-concept" than anything. Because of this I haven't yet implemented a feature where you can point a packageable binary at some remapping DSL file and have it dynamically load the remapping definition.

However, I can definitely see this as an end state. And when it does reach that state, the performance won't be any different than its current state -- the result of loading a DSL file would be to initialize a the same data structure produce by the proc macro DSL in the current version.

I suspect the performance of `qsk` is probably pretty good as far as a general-purpose keyboard remapper goes. I would like to write some benchmark tests to get an idea of what kind of input lag it introduces then experiment with reducing the overall number of heap allocations (eg by pre-allocating a pool of `InputEvents` and implementing some kind of system where instances are borrowed for a time as input events are detected from the source and new ones generated during transformation) to see what kind of performance improvements come from that.

> What do you think? I'd be very excited to lend my hand if you were to go all-in on this.

That would be spectacular! I like your enthusiasm and your ideas. I have a kind of roadmap in my personal notes that I'd be happy to share in a few weeks when I am ready to start looking at this code again.

**Comment by waynr** [comment]
@smallstepman FYI, I came across another rust-based keyboard remapper: https://crates.io/crates/ktrl. Definitely more mature, but because of that it may be harder to add the kind of `no_std` feature that would be necessary for embedded use cases (that is, if I correctly understand no std as a requirement for embedded rust).

**Comment by smallstepman** [comment]
Hey! Sorry, been pretty busy lately. That's awesome you've set up a twitch stream, I'll surely come to say hello one day :)

Nice, I didn't know about ktrl! Such a shame it's no longer maintained. I also found this https://github.com/TeXitoi/keyberon which is no_std already (found it here https://github.com/EanNewton/Awesome-Keebs, maybe you'll find more interesting stuff there). 

To me, it looks like we could just try to study a bunch of code from other repositories, then come up with architecture/project structure for qsk, “borrow” the code from other projects (as long as it's MIT), and write the glue. What do you think?

One other feature, which I find crucial and missing from ZMK is the ability to plugin code from other repositories. To give you an example, PMW3360 is a popular laser sensor for mice and trackballs. The code driving 3360 is available but sits behind a nonfree license (e.g. https://github.com/nrfconnect/sdk-nrf/tree/332d2d1bc4aa335673aa0738e411aff0f2195915/drivers/sensor/pmw3360 ), therefore, if one would want to build a keyboard with ZMK and 3360, they would ultimately have to create a fork of ZMK, which is a bad bad idea, nobody would use that fork. I know people at ZMK already talked about sucha plugin system, with plans to develop such a feature, however, I don't know where it sits progress-wise. 

To be fully transparent, I have never dealt with embedded systems on this level - in the past I flashed few boards and that's it. I have a very mild understanding of how hard this stuff gonna be. I just assume it's going to be fun ^^. Where do you stand in the embedded world?

**Comment by smallstepman** [comment]
Hey waynr, hope everything is well at your end. I'm closing the issue since I've decided to stay with ZMK and kmonad.
